name: Test README Generation

on:
  pull_request:
    branches: ['**']
    paths:
      - '_README.md'
      - 'generate_readme.py'
      - '.github/workflows/test-readme.yml'
  workflow_dispatch:
  
jobs:
  test-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate README.md (Test Only)
        run: |
          python3 generate_readme.py _README.md > README.md

      - name: Show README.md output
        run: |
          cat README.md

      - name: Run Awesome Lint on Generated README
        run: npx awesome-lint README.md
